# original found at https://tech.nicolonsky.ch/github-actions-powershell-signing/
# this has been modified to suit

name: CI
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  continuous_integration:
    name: Publish artifact
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build archive
        shell: powershell
        run: |
          New-Item -Path .\build -ItemType Directory -ErrorAction Stop | Out-Null
          .\Tools\7-Zip\7z.exe a -mx9 -spf -t7z .\build\BiRaitBec_WorkBase_Improved_${{ github.ref_name }}.7z `@".\.github\build_manifest"
      - name: Upload artifact to actions
        uses: actions/upload-artifact@v3
        with:
          path: .\build\BiRaitBec_WorkBase_Improved_${{ github.ref_name }}.7z
      - name: Publish artifact to release
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/BiRaitBec_WorkBase_Improved_${{ github.ref_name }}.7z
